import arctic from './assets/arctic-retreat.webp';
import arcticAuroraPreview from './assets/arctic-aurora-preview.mp4';
import garden from './assets/bioluminescent-garden.webp';
import granularSignal from './assets/granular-signal.webp';
import chromaticFlow from './assets/chromatic-flow.webp';
import deepSea from './assets/deep-sea-pulse.webp';
import diamondIgnition from './assets/diamond-ignition.webp';
import digitalSand from './assets/digital-sand.webp';
import liquidChrome from './assets/liquid-chrome.webp';
import magneticGrid from './assets/magnetic-grid.webp';
import neonTides from './assets/neon-tides.webp';
import organicVectorField from './assets/organic-vector-field.webp';
import particles from './assets/particle-orbit.webp';
import rainGlass from './assets/rain-glass.webp';
import radialConstellation from './assets/radial-constellation.webp';
import starMap from './assets/star-map.webp';
import stillwaterDawn from './assets/stillwater-dawn.webp';
import transit from './assets/night-transit.webp';
import nightTransitPreview from './assets/night-transit-preview.mp4';

export const WALLPAPERS = [
  {
    id: 1,
    title: 'Arctic Solitude',
    author: 'northbound',
    type: 'Obrázek',
    image: arctic,
    size: '12,8 MB',
    sizeMb: 12.8,
    accent: '#9dd6ff',
    featured: true,
    downloads: 8200,
    addedAt: '2026-08-18',
    tags: ['klid', 'soustředění', 'hory', 'noc'],
    description: 'Klidná horská krajina, která na ploše vytvoří prostor pro nerušenou práci.',
  },
  {
    id: 2,
    title: 'Particle Current',
    author: 'serein labs',
    type: 'Interaktivní',
    image: particles,
    size: '4,2 MB',
    sizeMb: 4.2,
    accent: '#b89cff',
    downloads: 7100,
    addedAt: '2026-08-20',
    tags: ['částice', 'energie', 'barevné'],
    description: 'Proud světelných částic reagující na pohyb kurzoru.',
  },
  {
    id: 3,
    title: 'Midnight Transit',
    author: 'framefield',
    type: 'Video',
    image: transit,
    video: nightTransitPreview,
    size: '86,4 MB',
    sizeMb: 86.4,
    accent: '#76d5dd',
    downloads: 9600,
    addedAt: '2026-08-12',
    tags: ['město', 'noc', 'déšť'],
    description: 'Noční město v pomalém filmovém pohybu s odlesky po dešti.',
  },
  {
    id: 4,
    title: 'Silent Aurora',
    author: 'northbound',
    type: 'Video',
    image: arctic,
    video: arcticAuroraPreview,
    size: '48,1 MB',
    sizeMb: 48.1,
    accent: '#71dbe8',
    position: 'center 30%',
    downloads: 5400,
    addedAt: '2026-08-15',
    tags: ['klid', 'soustředění', 'polární záře'],
    description: 'Jemně se proměňující polární záře pro klidný pracovní prostor.',
  },
  {
    id: 5,
    title: 'Violet Gravity',
    author: 'serein labs',
    type: 'Interaktivní',
    image: particles,
    size: '5,7 MB',
    sizeMb: 5.7,
    accent: '#ff92bd',
    position: '70% center',
    downloads: 6300,
    addedAt: '2026-08-21',
    tags: ['částice', 'fialová', 'energie'],
    description: 'Fialové částice kroužící kolem kurzoru v měkkém gravitačním poli.',
  },
  {
    id: 6,
    title: 'After the Rain',
    author: 'framefield',
    type: 'Obrázek',
    image: transit,
    size: '16,9 MB',
    sizeMb: 16.9,
    accent: '#f5b86a',
    position: 'left center',
    downloads: 4800,
    addedAt: '2026-08-10',
    tags: ['město', 'déšť', 'soustředění'],
    description: 'Tiché město po dešti s teplými odlesky pouličních světel.',
  },
  {
    id: 7,
    title: 'Neon Tides',
    author: 'open current',
    type: 'Interaktivní',
    effect: 'tides',
    image: neonTides,
    size: '6,1 MB',
    sizeMb: 6.1,
    accent: '#42e8d2',
    downloads: 0,
    addedAt: '2026-08-21',
    tags: ['proudnice', 'tyrkysová', 'klid', 'soustředění'],
    description: 'Tekuté neonové proudnice, které se před kurzorem rozestoupí a za ním se pozvolna uzavřou.',
  },
  {
    id: 8,
    title: 'Rain Glass',
    author: 'framefield',
    type: 'Interaktivní',
    effect: 'rain',
    image: rainGlass,
    size: '7,4 MB',
    sizeMb: 7.4,
    accent: '#67cfff',
    downloads: 0,
    addedAt: '2026-08-21',
    tags: ['déšť', 'město', 'sklo', 'klid'],
    description: 'Kapky pomalu stékají po skle a před pohybem kurzoru se rozestupují jako v jemném poryvu větru.',
  },
  {
    id: 9,
    title: 'Bioluminescent Garden',
    author: 'verdant signal',
    type: 'Interaktivní',
    effect: 'garden',
    image: garden,
    size: '6,8 MB',
    sizeMb: 6.8,
    accent: '#62f0bd',
    downloads: 0,
    addedAt: '2026-08-21',
    tags: ['příroda', 'rostliny', 'bioluminiscence', 'klid', 'soustředění'],
    description: 'Světélkující rostliny se naklánějí ke kurzoru; kliknutí vyšle zahradou jemnou světelnou vlnu.',
  },
  {
    id: 10,
    title: 'Star Map',
    author: 'northbound',
    type: 'Interaktivní',
    effect: 'stars',
    image: starMap,
    size: '4,9 MB',
    sizeMb: 4.9,
    accent: '#9bb9ff',
    downloads: 0,
    addedAt: '2026-08-21',
    tags: ['hvězdy', 'vesmír', 'minimalistické', 'soustředění'],
    description: 'Hvězdy v okolí kurzoru se propojují do pomíjivých souhvězdí a kliknutím vznikne gravitační vlna.',
  },
  {
    id: 11,
    title: 'Liquid Chrome',
    author: 'formless studio',
    type: 'Interaktivní',
    effect: 'chrome',
    image: liquidChrome,
    size: '5,6 MB',
    sizeMb: 5.6,
    accent: '#d6edff',
    downloads: 0,
    addedAt: '2026-08-21',
    tags: ['kov', 'tekutina', 'minimalistické', 'futuristické'],
    description: 'Tekutý kov se pod kurzorem deformuje a kliknutí rozešle po jeho povrchu soustředné odrazové vlny.',
  },
  {
    id: 12,
    title: 'Digital Sand',
    author: 'serein labs',
    type: 'Interaktivní',
    effect: 'sand',
    image: digitalSand,
    size: '5,2 MB',
    sizeMb: 5.2,
    accent: '#ffb26b',
    downloads: 0,
    addedAt: '2026-08-21',
    tags: ['částice', 'písek', 'oranžová', 'energie'],
    description: 'Jemná digitální zrnka se sesypávají proudem a kurzor v nich vytváří víry a prázdné stopy.',
  },
  {
    id: 13,
    title: 'Deep Sea Pulse',
    author: 'abyssal light',
    type: 'Interaktivní',
    effect: 'sea',
    image: deepSea,
    size: '7,1 MB',
    sizeMb: 7.1,
    accent: '#78dfff',
    downloads: 0,
    addedAt: '2026-08-21',
    tags: ['oceán', 'medúzy', 'modrá', 'klid', 'soustředění'],
    description: 'Bioluminiscenční medúzy se vznášejí hlubinou a při přiblížení kurzoru zesílí svůj světelný pulz.',
  },
  {
    id: 14,
    title: 'Stillwater Dawn',
    author: 'northbound',
    type: 'Obrázek',
    image: stillwaterDawn,
    size: '1,4 MB',
    sizeMb: 1.4,
    accent: '#f2caa7',
    downloads: 0,
    addedAt: '2026-08-21',
    tags: ['relaxace', 'jezero', 'mlha', 'ráno', 'klid', 'soustředění'],
    description: 'Tiché ranní jezero zahalené jemnou mlhou a měkkým světlem pro klidný začátek i konec dne.',
  },
  {
    id: 15,
    title: 'Chromatic Flow',
    author: 'open current',
    type: 'Interaktivní',
    effect: 'fluid',
    image: chromaticFlow,
    size: '6,4 MB',
    sizeMb: 6.4,
    accent: '#67d7ff',
    downloads: 0,
    addedAt: '2026-08-21',
    tags: ['kapalina', 'WebGL', 'barevné', 'energie'],
    description: 'Barevná kapalina se pod kurzorem stáčí do vírů, mísí odstíny a po kliknutí vyšle scénou nový proud.',
  },
  {
    id: 16,
    title: 'Magnetic Grid',
    author: 'field theory',
    type: 'Interaktivní',
    effect: 'magnetic',
    image: magneticGrid,
    size: '3,8 MB',
    sizeMb: 3.8,
    accent: '#d7ff63',
    downloads: 0,
    addedAt: '2026-08-21',
    tags: ['body', 'mřížka', 'minimalistické', 'soustředění'],
    description: 'Pravidelná mřížka bodů se přitahuje ke kurzoru a po jeho odchodu se pružně a plynule vrací do původního tvaru.',
  },
  {
    id: 17,
    title: 'Diamond Ignition',
    author: 'field theory',
    type: 'Interaktivní',
    effect: 'diamond',
    image: diamondIgnition,
    size: '4,1 MB',
    sizeMb: 4.1,
    accent: '#cdb8ff',
    downloads: 0,
    addedAt: '2026-08-21',
    tags: ['mřížka', 'světlo', 'minimalistické', 'klid', 'soustředění'],
    description: 'Jemnou diagonální mřížkou putují seedované světelné zážehy, které se z uzlů rozbíhají do čtyř směrů.',
  },
  {
    id: 18,
    title: 'Radial Constellation',
    author: 'field theory',
    type: 'Interaktivní',
    effect: 'constellation',
    image: radialConstellation,
    size: '4,6 MB',
    sizeMb: 4.6,
    accent: '#e2d2ff',
    downloads: 0,
    addedAt: '2026-08-21',
    tags: ['síť', 'částice', 'minimalistické', 'klid', 'soustředění'],
    description: 'Radiální síť jemně dýchá a prohýbá svá vlákna; uzly v blízkosti kurzoru ustupují a pružně se vracejí.',
  },
  {
    id: 19,
    title: 'Organic Vector Field',
    author: 'field theory',
    type: 'Interaktivní',
    effect: 'vector',
    image: organicVectorField,
    size: '4,3 MB',
    sizeMb: 4.3,
    accent: '#d7ff63',
    downloads: 0,
    addedAt: '2026-08-21',
    tags: ['vektory', 'tok', 'minimalistické', 'energie', 'soustředění'],
    description: 'Stovky drobných šipek sledují organické proudové pole a v okolí kurzoru se plynule natáčejí jeho směrem.',
  },
  {
    id: 20,
    title: 'Granular Signal',
    author: 'field theory',
    type: 'Interaktivní',
    effect: 'granular',
    image: granularSignal,
    size: '4,0 MB',
    sizeMb: 4.0,
    accent: '#d7ff63',
    downloads: 0,
    addedAt: '2026-08-21',
    tags: ['částice', 'síť', 'minimalistické', 'klid', 'soustředění'],
    description: 'Tiché granularní pole kolem kurzoru rozsvítí drobné částice a odhalí krátká spojení mezi blízkými body.',
  },
  {
    id: 21,
    title: 'Caustic Lagoon',
    author: 'abyssal light',
    type: 'Interaktivní',
    effect: 'caustics',
    image: deepSea,
    size: '2,9 MB',
    sizeMb: 2.9,
    accent: '#67d7ff',
    downloads: 0,
    addedAt: '2026-09-11',
    tags: ['voda', 'WebGL', 'kaustiky', 'klid', 'soustředění'],
    description: 'Plytká laguna s jemnými vodními kaustikami; kurzor mírní hladinu, vyzařuje vlnky a rozsvěcí světelný kužel pod hladinou.',
  },
  {
    id: 22,
    title: 'Aurora Drift',
    author: 'northbound',
    type: 'Interaktivní',
    effect: 'aurora',
    image: arctic,
    size: '3,4 MB',
    sizeMb: 3.4,
    accent: '#71dbe8',
    downloads: 0,
    addedAt: '2026-09-11',
    tags: ['polární záře', 'WebGL', 'světlo', 'klid', 'noční obloha'],
    description: 'Tři závěsy polární záře dýchají nad noční oblohou; kurzor je natáčí, zahušťuje jejich paprsky a rozsvěcí fosforescentní halo.',
  },
  {
    id: 23,
    title: 'Particle Nebula',
    author: 'serein labs',
    type: 'Interaktivní',
    effect: 'nebula',
    image: starMap,
    size: '3,1 MB',
    sizeMb: 3.1,
    accent: '#cdb8ff',
    downloads: 0,
    addedAt: '2026-09-11',
    tags: ['částice', 'WebGL', 'vesmír', 'energie', 'soustředění'],
    description: 'Tisíce GPU částic krouží v mlhovině kolem čtyř center; kurzor je víří a kliknutí vyšle gravitační puls, který je rozhodí.',
  },
  {
    id: 24,
    title: 'Mercury Tide',
    author: 'formless studio',
    type: 'Interaktivní',
    effect: 'metal',
    image: liquidChrome,
    size: '3,6 MB',
    sizeMb: 3.6,
    accent: '#c4e7ff',
    downloads: 0,
    addedAt: '2026-09-11',
    tags: ['kvapkový kov', 'WebGL', 'reflexe', 'minimalistické', 'energie'],
    description: 'Tmavý rtuťový povrch odráží studiová světla; kurzor do něj zatlačí důlek, kliknutí upustí těžkou kapku s jasnou paprskovou vlnou.',
  },
  {
    id: 25,
    title: 'Ion Storm',
    author: 'field theory',
    type: 'Interaktivní',
    effect: 'plasma',
    image: rainGlass,
    size: '4,2 MB',
    sizeMb: 4.2,
    accent: '#9ab8ff',
    downloads: 0,
    addedAt: '2026-09-11',
    tags: ['blesk', 'WebGL', 'bouřka', 'energie', 'noční obloha'],
    description: 'Bouřková obloha s blesky mezi třemi bouřkovými cellami; kurzor přitahuje výboje a nabíjí vzduch, kliknutí spustí plnou rázovou ránu.',
  },
  {
    id: 26,
    title: 'Event Horizon',
    author: 'abyssal light',
    type: 'Interaktivní',
    effect: 'blackhole',
    image: starMap,
    size: '3,8 MB',
    sizeMb: 3.8,
    accent: '#f0a960',
    downloads: 0,
    addedAt: '2026-09-11',
    tags: ['černá díra', 'WebGL', 'gravitace', 'vesmír', 'klid'],
    description: 'Gravitační čočka ohýbá hvězdné pole kolem horizontu; kurzor přesouvá singularitu, kliknutí zvyší hmotnost — akreční disk více svítí a prstence se roztáhnou.',
  },
].map((item) => ({
  ...item,
  searchText: `${item.title} ${item.author} ${item.type} ${item.tags.join(' ')}`.toLocaleLowerCase('cs'),
}));

export const TYPE_FILTERS = ['Vše', 'Obrázky', 'Video', 'Interaktivní'];

export const SORT_OPTIONS = [
  { value: 'popular', label: 'Nejoblíbenější' },
  { value: 'newest', label: 'Nejnovější' },
  { value: 'name', label: 'Podle názvu' },
  { value: 'smallest', label: 'Nejmenší soubor' },
];

export const VIEW_DEFINITIONS = {
  discover: { title: 'Objevovat', eyebrow: 'MARKETPLACE' },
  library: { title: 'Knihovna', eyebrow: 'VAŠE TAPETY' },
  installed: { title: 'Nainstalované', eyebrow: 'TOTO ZAŘÍZENÍ' },
  favorites: { title: 'Moje oblíbené', eyebrow: 'KOLEKCE' },
  focus: { title: 'Klid a soustředění', eyebrow: 'KOLEKCE' },
  settings: { title: 'Nastavení', eyebrow: 'OPENLBG' },
};
